@startuml

title __CARD's Class Diagram__\n

  namespace de.gematik.ti.cardreader.provider.api {
    namespace card {
      class de.gematik.ti.cardreader.provider.api.card.Atr {
          - atrRaw : byte[]
          + Atr()
          + getBytes()
      }
    }
  }
  

  namespace de.gematik.ti.cardreader.provider.api {
    namespace card {
      class de.gematik.ti.cardreader.provider.api.card.CardException {
          + CardException()
          + CardException()
      }
    }
  }
  

  namespace de.gematik.ti.cardreader.provider.api {
    namespace card {
      enum CardProtocol {
        T0
        T1
        T15
        rawValue
      }
    }
  }
  

  namespace de.gematik.ti.cardreader.provider.api {
    namespace card {
      interface de.gematik.ti.cardreader.provider.api.card.ICard {
          {abstract} + disconnect()
          {abstract} + getATR()
          {abstract} + getProtocol()
          {abstract} + openBasicChannel()
          {abstract} + openLogicalChannel()
      }
    }
  }
  

  namespace de.gematik.ti.cardreader.provider.api {
    namespace card {
      interface de.gematik.ti.cardreader.provider.api.card.ICardChannel {
          {abstract} + close()
          {abstract} + getCard()
          {abstract} + getChannelNumber()
          {abstract} + getMaxMessageLength()
          {abstract} + getMaxResponseLength()
          {abstract} + isExtendedLengthSupported()
          {abstract} + transmit()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
