@startuml



  namespace de.gematik.ti.cardreader.provider.api {
    namespace entities {
      interface de.gematik.ti.cardreader.provider.api.entities.IProviderDescriptor {
          {abstract} + getClassName()
          {abstract} + getDescription()
          {abstract} + getLicense()
          {abstract} + getName()
          {abstract} + getShortDescription()
      }
    }
  }
  

  namespace de.gematik.ti.cardreader.provider.api {
    namespace entities {
      class de.gematik.ti.cardreader.provider.api.entities.ProviderDescriptor {
          - className : String
          - description : String
          - license : String
          - name : String
          {static} - serialVersionUID : long
          - shortDescription : String
          + ProviderDescriptor()
          + getClassName()
          + getDescription()
          + getLicense()
          + getName()
          + getShortDescription()
          + setClassName()
          + setDescription()
          + setLicense()
          + setShortDescription()
      }
    }
  }
  

  de.gematik.ti.cardreader.provider.api.entities.ProviderDescriptor .up.|> de.gematik.ti.cardreader.provider.api.entities.IProviderDescriptor









@enduml
